import { chat } from "@/lib/ai/client";
import { logAiCost } from "./ai-cost";

export type KimiClassificationResult = {
  classification: {
    batchType: string | null;
    confidence: number;
    reason: string;
  };
  enrichment: {
    summary?: string;
    suggestedPriority?: string;
    suggestedTags?: string[];
  };
};

/**
 * Classify an inbox item using Kimi (via OpenRouter).
 * Also returns enrichment data (summary, priority, tags).
 * Returns null on failure.
 */
export async function classifyWithKimi(
  item: {
    id: string;
    connector: string;
    sender: string;
    senderName: string | null;
    subject: string;
    content: string;
  },
  guidanceNotes: string[]
): Promise<KimiClassificationResult | null> {
  const guidanceBlock =
    guidanceNotes.length > 0
      ? `\nGUIDANCE NOTES (use these to inform your classification):\n${guidanceNotes.map((g) => `- ${g}`).join("\n")}\n`
      : "";

  const systemPrompt = `You are a triage classifier. Classify items into groups or return null for individual attention.

Groups:
- "notifications": Automated tool/system messages: CI/CD failures, bot alerts, deployment notifications, device sign-ins, OAuth alerts, app notifications (Figma, Slack, GitHub, Airtable, Granola, etc.), confirmation codes. These are notifications FROM tools ABOUT activity — even if they mention a person's name (e.g. "Luli replied to a thread in Figma" is a notification, not a personal message).
- "finance": Financial notifications: invoice alerts, purchase orders, payment confirmations (Venmo, PayPal), credit card charges, billing reminders, payroll, insurance, workers comp. Includes both automated and semi-automated financial communications.
- "newsletters": Marketing emails, industry digests, job boards, subscription content, press releases, analytics reports, LinkedIn/social media digests.
- "calendar": Meeting invites, calendar acceptances/declines, RSVPs, scheduling changes, event updates.
- "spam": Cold outreach from unknown senders, junk mail, unsolicited sales pitches.
- null: Use ONLY for direct personal messages from a real person that require a personal response — e.g. "Hey, are you free for lunch?" or "Here's the doc you asked for". A real person writing directly to you about something specific.

KEY: If a message is generated by or routed through an app/tool/service, it belongs in a group — even if it references or is from a real person. Only use null for genuine 1:1 human correspondence.
${guidanceBlock}
Respond with ONLY valid JSON, no markdown fences:
{
  "batchType": "notifications"|"finance"|"newsletters"|"calendar"|"spam"|null,
  "confidence": 0.0-1.0,
  "reason": "brief explanation",
  "enrichment": {
    "summary": "1-2 sentence summary of the item",
    "suggestedPriority": "urgent|high|normal|low",
    "suggestedTags": ["tag1", "tag2"]
  }
}`;

  const input = `Classify this inbox item:

- Source: ${item.connector}
- From: ${item.senderName || item.sender} <${item.sender}>
- Subject: ${item.subject}
- Content: ${item.content.slice(0, 1500)}`;

  try {
    const response = await chat(input, systemPrompt);

    // Fire-and-forget cost logging
    logAiCost({
      provider: "kimi",
      operation: "classify",
      itemId: item.id,
    }).catch((err) =>
      console.error("[Classify Kimi] Failed to log AI cost:", err)
    );

    // Parse JSON from response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.warn("[Classify Kimi] No JSON found in response");
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]);

    return {
      classification: {
        batchType: parsed.batchType ?? null,
        confidence:
          typeof parsed.confidence === "number"
            ? Math.max(0, Math.min(1, parsed.confidence))
            : 0,
        reason: String(parsed.reason || "No reason provided"),
      },
      enrichment: {
        summary: parsed.enrichment?.summary,
        suggestedPriority: parsed.enrichment?.suggestedPriority,
        suggestedTags: Array.isArray(parsed.enrichment?.suggestedTags)
          ? parsed.enrichment.suggestedTags
          : undefined,
      },
    };
  } catch (error) {
    console.error("[Classify Kimi] Classification failed:", error);
    return null;
  }
}
